# fly.toml app configuration file generated for echo-bot-dev on 2024-01-09T14:17:07+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "echo-bot-dev"
primary_region = "yul"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_URL = "https://alpha.echonft.xyz/"
  PORT = "8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
