# fly.toml app configuration file generated for echo-bot-tmp on 2024-02-09T04:26:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echo-bot-testnet'
primary_region = 'yul'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[services]]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  handlers = ["http"]
  port = 1234

