# fly.toml app configuration file generated for echo-bot-tmp on 2024-02-09T04:26:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echobot'
primary_region = 'yul'

[build]
image = "registry.fly.io/echobot:latest"

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['app']
