# fly.toml app configuration file generated for echo-bot-tmp on 2024-02-09T04:26:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echo-bot-tmp'
primary_region = 'yul'

[build]

[env]
  PORT = '8080'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
