export const OFFER_CREATED = 'OFFER_CREATED'
export const OFFER_EXECUTED = 'OFFER_EXECUTED'
export const OFFER_CANCELLED = 'OFFER_CANCELLED'
export const OFFER_ACCEPTED = 'OFFER_ACCEPTED'
export const OFFER_REDEEMED = 'OFFER_REDEEMED'
export const ECHO_EVENT_TYPES = [
  OFFER_CREATED,
  OFFER_ACCEPTED,
  OFFER_EXECUTED,
  OFFER_CANCELLED,
  OFFER_REDEEMED
] as const
