# fly.toml app configuration file generated for echo-helper-dev on 2024-01-09T14:45:11+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "echo-helper-dev"
primary_region = "yul"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
