export const SizeXXS = 'Extra Extra Small'
export const SizeXS = 'Extra Small'
export const SizeSM = 'Small'
export const SizeMD = 'Medium'
export const SizeLG = 'Large'
export const SizeXL = 'Extra Large'
export const SizeXXL = 'Extra Extra Large'
