export const LISTING_STATE_OPEN = 'OPEN'
export const LISTING_STATE_OFFERS_PENDING = 'OFFERS_PENDING'
export const LISTING_STATE_PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED'
export const LISTING_STATE_FULFILLED = 'FULFILLED'
export const LISTING_STATE_CANCELLED = 'CANCELLED'
export const LISTING_STATE_EXPIRED = 'EXPIRED'

export const LISTING_STATES = [
  LISTING_STATE_OPEN,
  LISTING_STATE_OFFERS_PENDING,
  LISTING_STATE_PARTIALLY_FULFILLED,
  LISTING_STATE_FULFILLED,
  LISTING_STATE_CANCELLED,
  LISTING_STATE_EXPIRED
] as const
