export const OFFER_STATE_OPEN = 'OPEN'
export const OFFER_STATE_ACCEPTED = 'ACCEPTED'
export const OFFER_STATE_CANCELLED = 'CANCELLED'
export const OFFER_STATE_REJECTED = 'REJECTED'
export const OFFER_STATE_COMPLETED = 'COMPLETED'
export const OFFER_STATES = [
  OFFER_STATE_OPEN,
  OFFER_STATE_ACCEPTED,
  OFFER_STATE_CANCELLED,
  OFFER_STATE_REJECTED,
  OFFER_STATE_COMPLETED
] as const
