export enum CollectionReferenceName {
  ACCOUNTS = 'accounts',
  COLLECTIONS = 'nft-collections',
  COLLECTION_DISCORD_GUILDS = 'nft-collection-discord-guilds',
  COLLECTION_SWAPS_COUNT = 'nft-collection-swaps-count',
  NFTS = 'nfts',
  NONCES = 'nonces',
  OFFER_SIGNATURES = 'offer-signatures',
  OFFER_THREADS = 'offer-threads',
  OFFER_THREADS_CLOSE_REQUEST = 'offer-threads-close-requests',
  OFFER_UPDATES = 'offer-updates',
  OFFERS = 'offers',
  LISTING_OFFERS = 'listing-offers',
  LISTING_POSTS = 'listing-posts',
  LISTINGS = 'listings',
  SESSIONS = 'sessions',
  SWAPS = 'swaps',
  USERS = 'users',
  WALLETS = 'wallets'
}
