export enum RequestForOfferState {
  CREATED = 'CREATED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED'
}
