import {
  NAVIGATION_EXPLORE,
  NAVIGATION_LISTINGS,
  NAVIGATION_NFTS,
  NAVIGATION_OFFERS,
  NAVIGATION_PENDING_OFFERS,
  NAVIGATION_SWAPS
} from '@echo/ui/constants/navigation-item'

export type ProfileNavigationItem =
  | typeof NAVIGATION_NFTS
  | typeof NAVIGATION_LISTINGS
  | typeof NAVIGATION_EXPLORE
  | typeof NAVIGATION_OFFERS
  | typeof NAVIGATION_PENDING_OFFERS
  | typeof NAVIGATION_SWAPS
