import {
  NAVIGATION_LISTINGS_CREATED,
  NAVIGATION_LISTINGS_RECEIVED,
  NAVIGATION_NFTS,
  NAVIGATION_OFFERS_CREATED,
  NAVIGATION_OFFERS_RECEIVED,
  NAVIGATION_SWAPS
} from '@echo/ui/constants/navigation-item'

export type ProfileNavigationItem =
  | typeof NAVIGATION_NFTS
  | typeof NAVIGATION_LISTINGS_CREATED
  | typeof NAVIGATION_LISTINGS_RECEIVED
  | typeof NAVIGATION_OFFERS_CREATED
  | typeof NAVIGATION_OFFERS_RECEIVED
  | typeof NAVIGATION_SWAPS
