// TODO Update status
export enum SwapState {
  PENDING_APPROVALS = 'PENDING_APPROVALS',
  SENDER_APPROVED = 'SENDER_APPROVED',
  RECEIVER_APPROVED = 'RECEIVER_APPROVED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED'
}
