export const OFFER_STATE_UPDATE_TRIGGER_REASON_OWNERSHIP_CHANGED = 'ownership-changed' as const
export const OFFER_STATE_UPDATE_TRIGGER_REASON_APPROVAL_REVOKED = 'approval-revoked' as const
export const OFFER_STATE_UPDATE_TRIGGER_REASONS = [
  OFFER_STATE_UPDATE_TRIGGER_REASON_OWNERSHIP_CHANGED,
  OFFER_STATE_UPDATE_TRIGGER_REASON_APPROVAL_REVOKED
] as const
