export const PAGE_LAYOUT_BG_DEFAULT = 'default'
export const PAGE_LAYOUT_BG_HOME = 'home'
export const PAGE_LAYOUT_BG_COLLECTIONS = 'collections'
export const PAGE_LAYOUT_BG_GREEN_GRADIENT = 'green-gradient'
export const PAGE_LAYOUT_BG_YELLOW_GRADIENT = 'yellow-gradient'
export const PAGE_LAYOUT_BG_RED_GRADIENT = 'red-gradient'
export const PAGE_LAYOUT_BG_SUCCESS = 'success'

export const PAGE_LAYOUT_BACKGROUNDS = [
  PAGE_LAYOUT_BG_DEFAULT,
  PAGE_LAYOUT_BG_HOME,
  PAGE_LAYOUT_BG_COLLECTIONS,
  PAGE_LAYOUT_BG_GREEN_GRADIENT,
  PAGE_LAYOUT_BG_YELLOW_GRADIENT,
  PAGE_LAYOUT_BG_RED_GRADIENT,
  PAGE_LAYOUT_BG_SUCCESS
] as const
