export const PICTURE_SIZE_LOGIN_BUTTON = 32
export const PICTURE_SIZE_PROFILE_MD = 128
export const PICTURE_SIZE_PROFILE_ROUNDED = PICTURE_SIZE_PROFILE_MD
export const PICTURE_SIZE_PROFILE_SM = PICTURE_SIZE_PROFILE_MD
export const PICTURE_SIZE_PROFILE_LG = 256
export const PICTURE_SIZE_CARD = PICTURE_SIZE_PROFILE_LG
export const PICTURE_SIZE_BANNER = 4096
export const PICTURE_SIZE_NFT_THUMBNAIL = PICTURE_SIZE_PROFILE_MD
export const PICTURE_SIZE_COLLECTION_TILE = 512

export const PICTURE_SIZES = [
  PICTURE_SIZE_LOGIN_BUTTON,
  PICTURE_SIZE_PROFILE_MD,
  PICTURE_SIZE_PROFILE_LG,
  PICTURE_SIZE_COLLECTION_TILE,
  PICTURE_SIZE_BANNER
] as const
