name: 'Test code coverage'

on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                version: latest
                run_install: true

            - name: Run tests
              run: pnpm ci:test

            - name: Jest Coverage Comment
              uses: MishaKav/jest-coverage-comment@main
              with:
                multiple-files: |
                  lib/utils, ./coverage/lib/utils/coverage-summary.json
                multiple-junitxml-files: |
                  lib/utils, ./coverage/lib/utils/junit.xml
