name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run test coverage
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                package-manager: pnpm
                test-script: pnpm ci:test

