name: 'Test code coverage'

on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
              with:
                version: latest

            - name: Run tests
              run: pnpm frontend:build

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2.6.2
              if: always()
              with:
                files: |
                  coverage/**/*.xml
                  coverage/**/*.json

