name: Deploy Bot on Fly
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly/applications/bot/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
