name: 'Linting'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: bot lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/bot
      - name: frontend lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/frontend
      - name: storybook lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/storybook
      - name: alchemy lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/alchemy
      - name: api lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/api
      - name: firestore lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/firestore
      - name: firestore-functions lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/firestore-functions
      - name: model lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/model
      - name: sentry lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/sentry
      - name: tasks lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/tasks
      - name: ui lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/ui
      - name: utils lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/utils
      - name: web3 lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/web3
      - name: web3-dom lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/web3-dom
