name: 'Linting'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: bot lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/bot -- --quiet
      - name: frontend lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/frontend -- --quiet
      - name: storybook lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/storybook -- --quiet
      - name: api lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/api -- --quiet
      - name: auth lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/auth -- --quiet
      - name: firestore lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/firestore -- --quiet
      - name: firestore-functions lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/firestore-functions -- --quiet
      - name: model lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/model -- --quiet
      - name: nft-scan lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/nft-scan -- --quiet
      - name: opensea lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/opensea -- --quiet
      - name: ui lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/ui -- --quiet
      - name: utils lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/utils -- --quiet
      - name: web3 lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/web3 -- --quiet
      - name: web3-dom lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint --filter=@echo/web3-dom -- --quiet
