name: 'Linting'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: @echo/bot lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/bot
      - name: @echo/frontend lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/frontend
      - name: @echo/helper lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/helper
      - name: @echo/storybook lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/storybook
      - name: @echo/alchemy lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/alchemy
      - name: @echo/api lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/api
      - name: @echo/firestore lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/firestore
      - name: @echo/model lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/model
      - name: @echo/ui lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/ui
      - name: @echo/utils lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/utils
      - name: @echo/web3 lint
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm exec turbo run lint:ci --filter=@echo/web3
