name: 'Prettier'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: bot prettier
        run: pnpm exec turbo run prettier --filter=@echo/bot -- --log-level=silent
      - name: firestore-functions prettier
        run: pnpm exec turbo run prettier --filter=@echo/firestore-functions -- --log-level=silent
      - name: frontend prettier
        run: pnpm exec turbo run prettier --filter=@echo/frontend -- --log-level=silent
      - name: storybook prettier
        run: pnpm exec turbo run prettier --filter=@echo/storybook -- --log-level=silent
      - name: backend prettier
        run: pnpm exec turbo run prettier --filter=@echo/backend -- --log-level=silent
      - name: firestore prettier
        run: pnpm exec turbo run prettier --filter=@echo/firestore -- --log-level=silent
      - name: model prettier
        run: pnpm exec turbo run prettier --filter=@echo/model -- --log-level=silent
      - name: nft-scan prettier
        run: pnpm exec turbo run prettier --filter=@echo/nft-scan -- --log-level=silent
      - name: routing prettier
        run: pnpm exec turbo run prettier --filter=@echo/routing -- --log-level=silent
      - name: tasks prettier
        run: pnpm exec turbo run prettier --filter=@echo/tasks -- --log-level=silent
      - name: ui prettier
        run: pnpm exec turbo run prettier --filter=@echo/ui -- --log-level=silent
      - name: utils prettier
        run: pnpm exec turbo run prettier --filter=@echo/utils -- --log-level=silent
      - name: web3 prettier
        run: pnpm exec turbo run prettier --filter=@echo/web3 -- --log-level=silent
      - name: web3-dom prettier
        run: pnpm exec turbo run prettier --filter=@echo/web3-dom -- --log-level=silent
