name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: bot tests
        run: pnpm exec turbo run test:ci --filter=@echo/bot
      - name: frontend tests
        run: pnpm exec turbo run test:ci --filter=@echo/frontend
      - name: firestore tests
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_TEST }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL_TEST }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY_TEST }}
        run: pnpm exec turbo run test:ci --filter=@echo/firestore
      - name: model tests
        run: pnpm exec turbo run test:ci --filter=@echo/model
      - name: nft-scan tests
        run: pnpm exec turbo run test:ci --filter=@echo/nft-scan
      - name: opensea tests
        run: pnpm exec turbo run test:ci --filter=@echo/opensea
      - name: ui tests
        run: pnpm exec turbo run test:ci --filter=@echo/ui
      - name: utils tests
        run: pnpm exec turbo run test:ci --filter=@echo/utils
      - name: web3 tests
        run: pnpm exec turbo run test:ci --filter=@echo/web3
      - name: web3-dom tests
        run: pnpm exec turbo run test:ci --filter=@echo/web3-dom
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: |
            app/bot, ./.coverage/app/bot/coverage-summary.json
            app/frontend, ./.coverage/app/frontend/coverage-summary.json
            lib/firestore, ./.coverage/lib/firestore/coverage-summary.json
            lib/model, ./.coverage/lib/model/coverage-summary.json
            lib/nft-scan, ./.coverage/lib/nft-scan/coverage-summary.json
            lib/opensea, ./.coverage/lib/opensea/coverage-summary.json
            lib/ui, ./.coverage/lib/ui/coverage-summary.json                  
            lib/utils, ./.coverage/lib/utils/coverage-summary.json
            lib/web3, ./.coverage/lib/web3/coverage-summary.json
            lib/web3-dom, ./.coverage/lib/web3-dom/coverage-summary.json
          multiple-junitxml-files: |
            app/bot, ./.coverage/app/bot/junit.xml
            app/frontend, ./.coverage/app/frontend/junit.xml
            lib/firestore, ./.coverage/lib/firestore/junit.xml
            lib/model, ./.coverage/lib/model/junit.xml
            lib/nft-scan, ./.coverage/lib/nft-scan/junit.xml
            lib/opensea, ./.coverage/lib/model/junit.xml
            lib/ui, ./.coverage/lib/ui/junit.xml                  
            lib/utils, ./.coverage/lib/utils/junit.xml
            lib/web3, ./.coverage/lib/web3/junit.xml
            lib/web3-dom, ./.coverage/lib/web3-dom/junit.xml
