name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: @echo/bot tests
        run: pnpm exec turbo run test:ci --filter=@echo/bot
      - name: @echo/frontend tests
        run: pnpm exec turbo run test:ci --filter=@echo/frontend
      - name: @echo/helper tests
        run: pnpm exec turbo run test:ci --filter=@echo/helper
      - name: @echo/alchemy tests
        run: pnpm exec turbo run test:ci --filter=@echo/alchemy
      - name: @echo/firestore tests
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_TEST }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL_TEST }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY_TEST }}
        run: pnpm exec turbo run test:ci --filter=@echo/firestore
      - name: @echo/model tests
        run: pnpm exec turbo run test:ci --filter=@echo/model
      - name: @echo/ui tests
        run: pnpm exec turbo run test:ci --filter=@echo/ui
      - name: @echo/utils tests
        run: pnpm exec turbo run test:ci --filter=@echo/utils
      - name: @echo/web3 tests
        run: pnpm exec turbo run test:ci --filter=@echo/web3
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: |
            app/bot, ./.coverage/app/bot/coverage-summary.json
            app/frontend, ./.coverage/app/frontend/coverage-summary.json
            app/helper, ./.coverage/app/helper/coverage-summary.json
            lib/alchemy, ./.coverage/lib/alchemy/coverage-summary.json
            lib/firestore, ./.coverage/lib/firestore/coverage-summary.json
            lib/model, ./.coverage/lib/model/coverage-summary.json
            lib/ui, ./.coverage/lib/ui/coverage-summary.json                  
            lib/utils, ./.coverage/lib/utils/coverage-summary.json
            lib/web3, ./.coverage/lib/web3/coverage-summary.json
          multiple-junitxml-files: |
            app/bot, ./.coverage/app/bot/junit.xml
            app/frontend, ./.coverage/app/frontend/junit.xml
            app/helper, ./.coverage/app/helper/junit.xml
            lib/alchemy, ./.coverage/lib/alchemy/junit.xml
            lib/firestore, ./.coverage/lib/firestore/junit.xml
            lib/model, ./.coverage/lib/model/junit.xml
            lib/ui, ./.coverage/lib/ui/junit.xml                  
            lib/utils, ./.coverage/lib/utils/junit.xml
            lib/web3, ./.coverage/lib/web3/junit.xml
