name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run tests
        run: pnpm run test
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: |
            app/bot, ./.coverage/app/bot/coverage-summary.json
            app/frontend, ./.coverage/app/frontend/coverage-summary.json
            lib/alchemy, ./.coverage/lib/alchemy/coverage-summary.json
            lib/api, ./.coverage/lib/api/coverage-summary.json
            lib/firestore, ./.coverage/lib/firestore/coverage-summary.json
            lib/model, ./.coverage/lib/model/coverage-summary.json
            lib/ui, ./.coverage/lib/ui/coverage-summary.json                  
            lib/utils, ./.coverage/lib/utils/coverage-summary.json
            lib/web3, ./.coverage/lib/web3/coverage-summary.json
          multiple-junitxml-files: |
            app/bot, ./.coverage/app/bot/junit.xml
            app/frontend, ./.coverage/app/frontend/junit.xml
            lib/alchemy, ./.coverage/lib/alchemy/junit.xml
            lib/api, ./.coverage/lib/api/junit.xml
            lib/firestore, ./.coverage/lib/firestore/junit.xml
            lib/model, ./.coverage/lib/model/junit.xml
            lib/ui, ./.coverage/lib/ui/junit.xml                  
            lib/utils, ./.coverage/lib/utils/junit.xml
            lib/web3, ./.coverage/lib/web3/junit.xml
