name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: bot tests
        run: pnpm exec turbo run test --filter=@echo/bot
      - name: frontend tests
        run: pnpm exec turbo run test --filter=@echo/frontend
      - name: auth tests
        run: pnpm exec turbo run test --filter=@echo/auth
      - name: firestore tests
        env:
          ENV: 'test'
          SECRET_MANAGER_EMAIL: ${{ secrets.SECRET_MANAGER_EMAIL_TEST }}
          SECRET_MANAGER_PRIVATE_KEY: ${{ secrets.SECRET_MANAGER_PRIVATE_KEY_TEST }}
        run: pnpm exec turbo run test --filter=@echo/firestore
      - name: model tests
        run: pnpm exec turbo run test --filter=@echo/model
      - name: nft-scan tests
        run: pnpm exec turbo run test --filter=@echo/nft-scan
      - name: opensea tests
        run: pnpm exec turbo run test --filter=@echo/opensea
      - name: ui tests
        run: pnpm exec turbo run test --filter=@echo/ui
      - name: utils tests
        run: pnpm exec turbo run test --filter=@echo/utils
      - name: web3 tests
        run: pnpm exec turbo run test --filter=@echo/web3
      - name: web3-dom tests
        run: pnpm exec turbo run test --filter=@echo/web3-dom
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: |
            app/bot, ./app/bot/test/.coverage/coverage-summary.json
            app/frontend, ./app/frontend/test/.coverage/coverage-summary.json
            lib/firestore, ./lib/firestore/test/.coverage/coverage-summary.json
            lib/model, ./lib/model/test/.coverage/coverage-summary.json
            lib/nft-scan, ./lib/nft-scan/test/.coverage/coverage-summary.json
            lib/opensea, ./lib/opensea/test/.coverage/coverage-summary.json
            lib/ui, ./lib/ui/test/.coverage/coverage-summary.json                  
            lib/utils, ./lib/utils/test/.coverage/coverage-summary.json
            lib/web3, ./lib/web3/test/.coverage/coverage-summary.json
            lib/web3-dom, ./lib/web3-dom/test/.coverage/coverage-summary.json
          multiple-junitxml-files: |
            app/bot, ./app/bot/test/.coverage/junit.xml
            app/frontend, ./app/frontend/test/.coverage/junit.xml
            lib/firestore, ./lib/firestore/test/.coverage/junit.xml
            lib/model, ./lib/model/test/.coverage/junit.xml
            lib/nft-scan, ./lib/nft-scan/test/.coverage/junit.xml
            lib/opensea, ./lib/model/jtest/.coverage/unit.xml
            lib/ui, ./lib/ui/test/.coverage/junit.xml                  
            lib/utils, ./lib/utils/test/.coverage/junit.xml
            lib/web3, ./lib/web3/test/.coverage/junit.xml
            lib/web3-dom, ./lib/web3-dom/test/.coverage/junit.xml
