name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JEST_JUNIT_OUTPUT_DIR: './test/.coverage'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: bot tests
        run: pnpm exec turbo run test:ci --filter=@echo/bot
      - name: backend tests
        run: pnpm exec turbo run test:ci --filter=@echo/backend
      - name: firestore tests
        env:
          ENV: 'test'
          SECRET_MANAGER_EMAIL: ${{ secrets.SECRET_MANAGER_EMAIL_TEST }}
          SECRET_MANAGER_PRIVATE_KEY: ${{ secrets.SECRET_MANAGER_PRIVATE_KEY_TEST }}
        run: pnpm exec turbo run test:ci --filter=@echo/firestore
      - name: model tests
        run: pnpm exec turbo run test:ci --filter=@echo/model
      - name: nft-scan tests
        run: pnpm exec turbo run test:ci --filter=@echo/nft-scan
      - name: routing tests
        run: pnpm exec turbo run test:ci --filter=@echo/routing
      - name: ui tests
        run: pnpm exec turbo run test:ci --filter=@echo/ui
      - name: utils tests
        run: pnpm exec turbo run test:ci --filter=@echo/utils
      - name: web3 tests
        run: pnpm exec turbo run test:ci --filter=@echo/web3
      - name: web3-dom tests
        run: pnpm exec turbo run test:ci --filter=@echo/web3-dom
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: |
            app/bot, ./app/bot/test/.coverage/coverage-summary.json
            lib/auth, ./lib/auth/test/.coverage/coverage-summary.json
            lib/backend, ./lib/backend/test/.coverage/coverage-summary.json
            lib/firestore, ./lib/firestore/test/.coverage/coverage-summary.json
            lib/model, ./lib/model/test/.coverage/coverage-summary.json
            lib/nft-scan, ./lib/nft-scan/test/.coverage/coverage-summary.json
            lib/opensea, ./lib/opensea/test/.coverage/coverage-summary.json
            lib/ui, ./lib/ui/test/.coverage/coverage-summary.json                  
            lib/utils, ./lib/utils/test/.coverage/coverage-summary.json
            lib/web3, ./lib/web3/test/.coverage/coverage-summary.json
            lib/web3-dom, ./lib/web3-dom/test/.coverage/coverage-summary.json
          multiple-junitxml-files: |
            app/bot, ./app/bot/test/.coverage/junit.xml
            lib/auth, ./lib/auth/test/.coverage/junit.xml
            lib/backend, ./lib/backend/test/.coverage/junit.xml
            lib/firestore, ./lib/firestore/test/.coverage/junit.xml
            lib/model, ./lib/model/test/.coverage/junit.xml
            lib/nft-scan, ./lib/nft-scan/test/.coverage/junit.xml
            lib/opensea, ./lib/model/jtest/.coverage/unit.xml
            lib/ui, ./lib/ui/test/.coverage/junit.xml                  
            lib/utils, ./lib/utils/test/.coverage/junit.xml
            lib/web3, ./lib/web3/test/.coverage/junit.xml
            lib/web3-dom, ./lib/web3-dom/test/.coverage/junit.xml
