name: 'Type checking'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: bot tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/bot
      - name: frontend tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/frontend
      - name: storybook tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/storybook
      - name: alchemy tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/alchemy
      - name: api tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/api
      - name: firestore tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/firestore
      - name: firestore-functions tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/firestore-functions
      - name: model tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/model
      - name: sentry tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/sentry
      - name: ui tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/ui
      - name: utils tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/utils
      - name: web3 tsc
        run: pnpm exec turbo run tsc:ci --filter=@echo/web3
