name: 'Type checking'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  tsc:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: bot tsc
        run: pnpm exec turbo run tsc --filter=@echo/bot
      - name: firestore-functions tsc
        run: pnpm exec turbo run tsc --filter=@echo/firestore-functions
      - name: frontend tsc
        run: pnpm exec turbo run tsc --filter=@echo/frontend
      - name: storybook tsc
        run: pnpm exec turbo run tsc --filter=@echo/storybook
      - name: api tsc
        run: pnpm exec turbo run tsc --filter=@echo/api
      - name: backend tsc
        run: pnpm exec turbo run tsc --filter=@echo/backend
      - name: firestore tsc
        run: pnpm exec turbo run tsc --filter=@echo/firestore
      - name: model tsc
        run: pnpm exec turbo run tsc --filter=@echo/model
      - name: nft-scan tsc
        run: pnpm exec turbo run tsc --filter=@echo/nft-scan
      - name: opensea tsc
        run: pnpm exec turbo run tsc --filter=@echo/opensea
      - name: routing tsc
        run: pnpm exec turbo run tsc --filter=@echo/routing
      - name: tasks tsc
        run: pnpm exec turbo run tsc --filter=@echo/tasks
      - name: ui tsc
        run: pnpm exec turbo run tsc --filter=@echo/ui
      - name: utils tsc
        run: pnpm exec turbo run tsc --filter=@echo/utils
      - name: web3 tsc
        run: pnpm exec turbo run tsc --filter=@echo/web3
      - name: web3-dom tsc
        run: pnpm exec turbo run tsc --filter=@echo/web3-dom
